package pdf;


/**
* pdf/_PDFServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Tuesday, May 19, 2026 1:21:26 PM GMT
*/

public class _PDFServiceStub extends org.omg.CORBA.portable.ObjectImpl implements pdf.PDFService
{

  public String mergePDF (String path1, String path2, String output)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("mergePDF", true);
                $out.write_string (path1);
                $out.write_string (path2);
                $out.write_string (output);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return mergePDF (path1, path2, output        );
            } finally {
                _releaseReply ($in);
            }
  } // mergePDF

  public String splitPDF (String path, int pages, String outputDir)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("splitPDF", true);
                $out.write_string (path);
                $out.write_long (pages);
                $out.write_string (outputDir);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return splitPDF (path, pages, outputDir        );
            } finally {
                _releaseReply ($in);
            }
  } // splitPDF

  public String extractPages (String path, int fromPage, int toPage, String output)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("extractPages", true);
                $out.write_string (path);
                $out.write_long (fromPage);
                $out.write_long (toPage);
                $out.write_string (output);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return extractPages (path, fromPage, toPage, output        );
            } finally {
                _releaseReply ($in);
            }
  } // extractPages

  public String deletePages (String path, int fromPage, int toPage, String output)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("deletePages", true);
                $out.write_string (path);
                $out.write_long (fromPage);
                $out.write_long (toPage);
                $out.write_string (output);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return deletePages (path, fromPage, toPage, output        );
            } finally {
                _releaseReply ($in);
            }
  } // deletePages

  public String addPassword (String path, String password, String output)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addPassword", true);
                $out.write_string (path);
                $out.write_string (password);
                $out.write_string (output);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return addPassword (path, password, output        );
            } finally {
                _releaseReply ($in);
            }
  } // addPassword

  public String convertToImages (String path, String outputDir)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("convertToImages", true);
                $out.write_string (path);
                $out.write_string (outputDir);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return convertToImages (path, outputDir        );
            } finally {
                _releaseReply ($in);
            }
  } // convertToImages

  public String extractText (String path)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("extractText", true);
                $out.write_string (path);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return extractText (path        );
            } finally {
                _releaseReply ($in);
            }
  } // extractText

  public String createPDF (String content, String output)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createPDF", true);
                $out.write_string (content);
                $out.write_string (output);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return createPDF (content, output        );
            } finally {
                _releaseReply ($in);
            }
  } // createPDF

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:pdf/PDFService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "pdf._PDFServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _PDFServiceStub
