package pdf;


/**
* pdf/PDFServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Tuesday, May 19, 2026 1:21:26 PM GMT
*/

public abstract class PDFServicePOA extends org.omg.PortableServer.Servant
 implements pdf.PDFServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("mergePDF", new java.lang.Integer (0));
    _methods.put ("splitPDF", new java.lang.Integer (1));
    _methods.put ("extractPages", new java.lang.Integer (2));
    _methods.put ("deletePages", new java.lang.Integer (3));
    _methods.put ("addPassword", new java.lang.Integer (4));
    _methods.put ("convertToImages", new java.lang.Integer (5));
    _methods.put ("extractText", new java.lang.Integer (6));
    _methods.put ("createPDF", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // pdf/PDFService/mergePDF
       {
         String path1 = in.read_string ();
         String path2 = in.read_string ();
         String output = in.read_string ();
         String $result = null;
         $result = this.mergePDF (path1, path2, output);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // pdf/PDFService/splitPDF
       {
         String path = in.read_string ();
         int pages = in.read_long ();
         String outputDir = in.read_string ();
         String $result = null;
         $result = this.splitPDF (path, pages, outputDir);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // pdf/PDFService/extractPages
       {
         String path = in.read_string ();
         int fromPage = in.read_long ();
         int toPage = in.read_long ();
         String output = in.read_string ();
         String $result = null;
         $result = this.extractPages (path, fromPage, toPage, output);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // pdf/PDFService/deletePages
       {
         String path = in.read_string ();
         int fromPage = in.read_long ();
         int toPage = in.read_long ();
         String output = in.read_string ();
         String $result = null;
         $result = this.deletePages (path, fromPage, toPage, output);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // pdf/PDFService/addPassword
       {
         String path = in.read_string ();
         String password = in.read_string ();
         String output = in.read_string ();
         String $result = null;
         $result = this.addPassword (path, password, output);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // pdf/PDFService/convertToImages
       {
         String path = in.read_string ();
         String outputDir = in.read_string ();
         String $result = null;
         $result = this.convertToImages (path, outputDir);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // pdf/PDFService/extractText
       {
         String path = in.read_string ();
         String $result = null;
         $result = this.extractText (path);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // pdf/PDFService/createPDF
       {
         String content = in.read_string ();
         String output = in.read_string ();
         String $result = null;
         $result = this.createPDF (content, output);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:pdf/PDFService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PDFService _this() 
  {
    return PDFServiceHelper.narrow(
    super._this_object());
  }

  public PDFService _this(org.omg.CORBA.ORB orb) 
  {
    return PDFServiceHelper.narrow(
    super._this_object(orb));
  }


} // class PDFServicePOA
