package pdf;


/**
* pdf/PDFServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Tuesday, May 19, 2026 1:21:26 PM GMT
*/

public interface PDFServiceOperations 
{
  String mergePDF (String path1, String path2, String output);
  String splitPDF (String path, int pages, String outputDir);
  String extractPages (String path, int fromPage, int toPage, String output);
  String deletePages (String path, int fromPage, int toPage, String output);
  String addPassword (String path, String password, String output);
  String convertToImages (String path, String outputDir);
  String extractText (String path);
  String createPDF (String content, String output);
} // interface PDFServiceOperations
