package pdf;

/**
* pdf/PDFServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Tuesday, May 19, 2026 1:21:26 PM GMT
*/

public final class PDFServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public pdf.PDFService value = null;

  public PDFServiceHolder ()
  {
  }

  public PDFServiceHolder (pdf.PDFService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = pdf.PDFServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    pdf.PDFServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return pdf.PDFServiceHelper.type ();
  }

}
