package pdf;


/**
* pdf/PDFService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Tuesday, May 19, 2026 1:21:26 PM GMT
*/

public interface PDFService extends PDFServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PDFService
